include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.req.gql.dart"
    - "**/*.var.gql.dart"
    - "**/*.data.gql.dart"
    - "prisma-submodule/**"
    - "examples/**/generated/**"
  errors:
    invalid_annotation_target: ignore
    avoid_print: ignore  # Allow print in CLI tools

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print
    - avoid_relative_lib_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - sort_pub_dependencies
    - unnecessary_await_in_return
    - use_super_parameters
