/// Schema registry generator using code_builder for type-safe AST generation.
// ignore_for_file: prefer_const_constructors
library;

import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:prisma_flutter_connector/src/generator/prisma_parser.dart';
import 'package:prisma_flutter_connector/src/generator/string_utils.dart';

/// Generates schema registry code from a parsed Prisma schema using code_builder.
class CbSchemaRegistryGenerator {
  final PrismaSchema schema;
  final bool serverMode;
  late final _formatter =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);

  CbSchemaRegistryGenerator(this.schema, {this.serverMode = false});

  String generate() {
    final runtimeImport = serverMode ? 'runtime_server.dart' : 'runtime.dart';

    // Build the registration statements for each model
    final registrations = <Code>[];
    for (final model in schema.models) {
      registrations.add(_buildModelRegistration(model));
    }

    final library = Library((b) => b
      ..comments.addAll([
        '/// Generated schema registry — DO NOT EDIT.',
        '///',
        '/// This file was generated by prisma_flutter_connector:generate.',
        '/// It registers all models, fields, and relations from the Prisma schema.',
      ])
      ..directives.add(
          Directive.import('package:prisma_flutter_connector/$runtimeImport'))
      ..body.add(Method((m) => m
        ..name = 'registerAllModels'
        ..docs.addAll([
          '/// Register all models and relations in the given [SchemaRegistry].',
          '///',
          '/// Call this once at application startup:',
          '/// ```dart',
          '/// registerAllModels(schemaRegistry);',
          '/// ```',
        ])
        ..returns = refer('void')
        ..requiredParameters.add(Parameter((p) => p
          ..name = 'registry'
          ..type = refer('SchemaRegistry')))
        ..body = Block.of(registrations))));

    final emitter = DartEmitter(useNullSafetySyntax: true);
    return _formatter.format('${library.accept(emitter)}');
  }

  Code _buildModelRegistration(PrismaModel model) {
    final tableName = model.tableName;
    final fields = <String>[];

    for (final field in model.fields) {
      if (field.isRelation) continue;
      final columnName = field.dbName ?? field.name;
      final dartType = _prismaTypeToDartType(field.type);

      final parts = <String>["name: '${field.name}'"];
      parts.add("columnName: '$columnName'");
      parts.add("type: '$dartType'");
      if (field.isId) parts.add('isId: true');
      if (field.isUnique) parts.add('isUnique: true');
      if (!field.isRequired) parts.add('isNullable: true');
      if (field.defaultValue != null) {
        parts.add("defaultValue: '${field.defaultValue}'");
      }

      fields.add("'${field.name}': FieldInfo(${parts.join(', ')})");
    }

    final relations = _resolveRelations(model);
    final relParts = relations.map((r) => "'${r.fieldName}': ${r.code}");

    final fieldMap = '{${fields.join(', ')}}';
    final relMap = relations.isEmpty ? 'const {}' : '{${relParts.join(', ')}}';

    return Code('''
      registry.registerModel(ModelSchema(
        name: '${model.name}',
        tableName: '$tableName',
        fields: $fieldMap,
        relations: $relMap,
      ));
    ''');
  }

  List<_RelEntry> _resolveRelations(PrismaModel model) {
    final entries = <_RelEntry>[];

    for (final field in model.fields) {
      if (!field.isRelation) continue;

      final target = field.type;
      final targetModel =
          schema.models.where((m) => m.name == target).firstOrNull;
      if (targetModel == null) continue;

      if (field.isList) {
        if (_isManyToMany(model, field, targetModel)) {
          final jt = _junctionTableName(model.name, target);
          final jc = model.name.compareTo(target) < 0 ? 'A' : 'B';
          final ic = model.name.compareTo(target) < 0 ? 'B' : 'A';
          entries.add(_RelEntry(
            fieldName: field.name,
            code: "RelationInfo.manyToMany("
                "name: '${field.name}', "
                "targetModel: '$target', "
                "joinTable: '$jt', "
                "joinColumn: '$jc', "
                "inverseJoinColumn: '$ic')",
          ));
        } else {
          final fk = _findForeignKey(targetModel, model.name);
          entries.add(_RelEntry(
            fieldName: field.name,
            code: "RelationInfo.oneToMany("
                "name: '${field.name}', "
                "targetModel: '$target', "
                "foreignKey: '$fk')",
          ));
        }
      } else {
        final fk = _findForeignKeyOnModel(model, target) ??
            _findForeignKeyFromField(field);
        if (fk == null) continue;

        final backRef = targetModel.fields
            .where((f) => f.isRelation && f.type == model.name && !f.isList);
        if (backRef.isNotEmpty) {
          entries.add(_RelEntry(
            fieldName: field.name,
            code: "RelationInfo.oneToOne("
                "name: '${field.name}', "
                "targetModel: '$target', "
                "foreignKey: '$fk', "
                "isOwner: true)",
          ));
        } else {
          entries.add(_RelEntry(
            fieldName: field.name,
            code: "RelationInfo.manyToOne("
                "name: '${field.name}', "
                "targetModel: '$target', "
                "foreignKey: '$fk')",
          ));
        }
      }
    }

    return entries;
  }

  bool _isManyToMany(
      PrismaModel model, PrismaField field, PrismaModel targetModel) {
    if (!field.isList) return false;
    if (field.relationFromFields?.isNotEmpty == true) return false;
    return targetModel.fields
        .where((f) => f.isRelation && f.type == model.name && f.isList)
        .isNotEmpty;
  }

  String _junctionTableName(String a, String b) {
    final sorted = [a, b]..sort();
    return '_${sorted[0]}To${sorted[1]}';
  }

  String _findForeignKey(PrismaModel target, String sourceModel) {
    for (final f in target.fields) {
      if (f.isRelation &&
          f.type == sourceModel &&
          f.relationFromFields?.isNotEmpty == true) {
        return f.relationFromFields!.first;
      }
    }
    return '${toLowerCamelCase(sourceModel)}Id';
  }

  String? _findForeignKeyOnModel(PrismaModel model, String target) {
    for (final f in model.fields) {
      if (f.isRelation &&
          f.type == target &&
          f.relationFromFields?.isNotEmpty == true) {
        return f.relationFromFields!.first;
      }
    }
    return null;
  }

  String? _findForeignKeyFromField(PrismaField field) {
    if (field.relationFromFields?.isNotEmpty == true) {
      return field.relationFromFields!.first;
    }
    return '${toLowerCamelCase(field.type)}Id';
  }

  String _prismaTypeToDartType(String t) => switch (t) {
        'String' => 'String',
        'Int' => 'int',
        'BigInt' => 'BigInt',
        'Float' || 'Decimal' => 'double',
        'Boolean' => 'bool',
        'DateTime' => 'DateTime',
        'Json' => 'Map<String, dynamic>',
        'Bytes' => 'List<int>',
        _ => t,
      };
}

class _RelEntry {
  final String fieldName;
  final String code;
  const _RelEntry({required this.fieldName, required this.code});
}
