/// Schema registry generator for automatic model/relation registration.
///
/// Generates a `schema_registry.g.dart` file that populates the SchemaRegistry
/// with all models, fields, and relations from the Prisma schema. This replaces
/// the need for manual schema registry maintenance.
library;

import 'package:prisma_flutter_connector/src/generator/prisma_parser.dart';
import 'package:prisma_flutter_connector/src/generator/string_utils.dart';

/// Generates schema registry code from a parsed Prisma schema.
class SchemaRegistryGenerator {
  final PrismaSchema schema;
  final bool serverMode;

  const SchemaRegistryGenerator(this.schema, {this.serverMode = false});

  /// Generate the schema registry file.
  String generate() {
    final buffer = StringBuffer();

    // File header
    final runtimeImport = serverMode ? 'runtime_server.dart' : 'runtime.dart';
    buffer.writeln('/// Generated schema registry — DO NOT EDIT.');
    buffer.writeln('///');
    buffer.writeln(
        '/// This file was generated by prisma_flutter_connector:generate.');
    buffer.writeln(
        '/// It registers all models, fields, and relations from the Prisma schema.');
    buffer.writeln('library;');
    buffer.writeln();
    buffer.writeln("import 'package:prisma_flutter_connector/$runtimeImport';");
    buffer.writeln();

    // Generate the registerAllModels function
    buffer.writeln(
        '/// Register all models and relations in the given [SchemaRegistry].');
    buffer.writeln('///');
    buffer.writeln('/// Call this once at application startup:');
    buffer.writeln('/// ```dart');
    buffer.writeln('/// registerAllModels(schemaRegistry);');
    buffer.writeln('/// ```');
    buffer.writeln('void registerAllModels(SchemaRegistry registry) {');

    for (final model in schema.models) {
      _generateModelRegistration(buffer, model);
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateModelRegistration(StringBuffer buffer, PrismaModel model) {
    final tableName = model.tableName;

    buffer.writeln('  registry.registerModel(ModelSchema(');
    buffer.writeln("    name: '${model.name}',");
    buffer.writeln("    tableName: '$tableName',");

    // Fields
    buffer.writeln('    fields: {');
    for (final field in model.fields) {
      if (field.isRelation) continue; // Skip relation fields

      final columnName = field.dbName ?? field.name;
      final dartType = _prismaTypeToDartType(field.type);

      buffer.write("      '${field.name}': FieldInfo(");
      buffer.write("name: '${field.name}', ");
      buffer.write("columnName: '$columnName', ");
      buffer.write("type: '$dartType'");
      if (field.isId) buffer.write(', isId: true');
      if (field.isUnique) buffer.write(', isUnique: true');
      if (!field.isRequired) buffer.write(', isNullable: true');
      if (field.defaultValue != null) {
        buffer.write(", defaultValue: '${field.defaultValue}'");
      }
      buffer.writeln('),');
    }
    buffer.writeln('    },');

    // Relations
    final relations = _resolveRelations(model);
    if (relations.isNotEmpty) {
      buffer.writeln('    relations: {');
      for (final rel in relations) {
        buffer.write("      '${rel.fieldName}': ");
        buffer.write(rel.code);
        buffer.writeln(',');
      }
      buffer.writeln('    },');
    }

    buffer.writeln('  ));');
    buffer.writeln();
  }

  /// Resolve all relation fields for a model, generating RelationInfo code.
  List<_RelationEntry> _resolveRelations(PrismaModel model) {
    final entries = <_RelationEntry>[];

    for (final field in model.fields) {
      if (!field.isRelation) continue;

      final targetModelName = field.type;
      final targetModel =
          schema.models.where((m) => m.name == targetModelName).firstOrNull;

      if (targetModel == null) continue;

      if (field.isList) {
        // Could be oneToMany or manyToMany
        if (_isManyToMany(model, field, targetModel)) {
          final junctionTable =
              _getJunctionTableName(model.name, targetModelName);
          // Prisma uses A/B columns based on alphabetical model name order
          final joinCol = model.name.compareTo(targetModelName) < 0 ? 'A' : 'B';
          final inverseCol =
              model.name.compareTo(targetModelName) < 0 ? 'B' : 'A';

          entries.add(_RelationEntry(
            fieldName: field.name,
            code: "RelationInfo.manyToMany(\n"
                "        name: '${field.name}',\n"
                "        targetModel: '$targetModelName',\n"
                "        joinTable: '$junctionTable',\n"
                "        joinColumn: '$joinCol',\n"
                "        inverseJoinColumn: '$inverseCol',\n"
                "      )",
          ));
        } else {
          // oneToMany — the FK is on the target model
          final fk = _findForeignKey(targetModel, model.name);
          entries.add(_RelationEntry(
            fieldName: field.name,
            code: "RelationInfo.oneToMany(\n"
                "        name: '${field.name}',\n"
                "        targetModel: '$targetModelName',\n"
                "        foreignKey: '$fk',\n"
                "      )",
          ));
        }
      } else {
        // manyToOne or oneToOne
        final fk = _findForeignKeyOnModel(model, targetModelName) ??
            _findForeignKeyFromRelationFields(field);

        if (fk != null) {
          // Check if the target also has a single (non-list) back-reference → oneToOne
          final backRef = targetModel.fields
              .where((f) => f.isRelation && f.type == model.name && !f.isList);
          if (backRef.isNotEmpty) {
            entries.add(_RelationEntry(
              fieldName: field.name,
              code: "RelationInfo.oneToOne(\n"
                  "        name: '${field.name}',\n"
                  "        targetModel: '$targetModelName',\n"
                  "        foreignKey: '$fk',\n"
                  "        isOwner: true,\n"
                  "      )",
            ));
          } else {
            entries.add(_RelationEntry(
              fieldName: field.name,
              code: "RelationInfo.manyToOne(\n"
                  "        name: '${field.name}',\n"
                  "        targetModel: '$targetModelName',\n"
                  "        foreignKey: '$fk',\n"
                  "      )",
            ));
          }
        }
      }
    }

    return entries;
  }

  /// Check if a list relation is M2M (both sides are lists).
  bool _isManyToMany(
      PrismaModel model, PrismaField field, PrismaModel targetModel) {
    // A relation is M2M if:
    // 1. This side is a list
    // 2. The target model has a list field pointing back to this model
    // 3. Neither side has explicit @relation(fields: [...])
    if (!field.isList) return false;

    final hasExplicitFk = field.relationFromFields?.isNotEmpty == true;
    if (hasExplicitFk) return false;

    final backRef = targetModel.fields
        .where((f) => f.isRelation && f.type == model.name && f.isList);
    return backRef.isNotEmpty;
  }

  /// Get the Prisma implicit junction table name (alphabetical order with underscore prefix).
  String _getJunctionTableName(String modelA, String modelB) {
    final sorted = [modelA, modelB]..sort();
    return '_${sorted[0]}To${sorted[1]}';
  }

  /// Find the FK field on targetModel that references sourceModelName.
  String _findForeignKey(PrismaModel targetModel, String sourceModelName) {
    // Look for an explicit @relation field pointing to sourceModel
    for (final field in targetModel.fields) {
      if (field.isRelation &&
          field.type == sourceModelName &&
          field.relationFromFields?.isNotEmpty == true) {
        return field.relationFromFields!.first;
      }
    }
    // Convention: sourceModelId in camelCase
    return '${toLowerCamelCase(sourceModelName)}Id';
  }

  /// Find the FK field on this model that references targetModelName.
  String? _findForeignKeyOnModel(PrismaModel model, String targetModelName) {
    for (final field in model.fields) {
      if (field.isRelation &&
          field.type == targetModelName &&
          field.relationFromFields?.isNotEmpty == true) {
        return field.relationFromFields!.first;
      }
    }
    return null;
  }

  /// Extract FK from the field's @relation(fields: [...]) attribute.
  String? _findForeignKeyFromRelationFields(PrismaField field) {
    if (field.relationFromFields?.isNotEmpty == true) {
      return field.relationFromFields!.first;
    }
    // Convention fallback
    return '${toLowerCamelCase(field.type)}Id';
  }

  String _prismaTypeToDartType(String prismaType) {
    switch (prismaType) {
      case 'String':
        return 'String';
      case 'Int':
        return 'int';
      case 'BigInt':
        return 'BigInt';
      case 'Float':
      case 'Decimal':
        return 'double';
      case 'Boolean':
        return 'bool';
      case 'DateTime':
        return 'DateTime';
      case 'Json':
        return 'Map<String, dynamic>';
      case 'Bytes':
        return 'List<int>';
      default:
        return prismaType;
    }
  }
}

class _RelationEntry {
  final String fieldName;
  final String code;

  const _RelationEntry({required this.fieldName, required this.code});
}
